#!/bin/bash

    readarray -t file < /etc/passwd
    i=0
    tags=""
    for item in ${file[@]}; do
        user=$(echo "$item" | cut -d':' -f 1)
        if [ "$(id $user 2>&1 > /dev/null)" != "" ]; then
            continue
        fi
        tags="$tags $i $user"
        users[$i]="$user"
        i=$(($i+1))
    done
    exec 3>&1
    result=$(dialog --backtitle "sm (Server Manager) - Usuarios y Grupos" \
    --clear  \
    --menu "Seleccione un usuario" 0 0 0 \
            $tags \
            2>&1 1>&3)
    return_value=$?
    exec 3>&-
    unset Selected
    if [ "$return_value" != "1" ] || [ "$return_value" != "255" ]; then
        Selected=${users[$result]}
    fi
    clear
    usermod -U $Selected