./" Este es el manpage para sm
.TH sm "V0.0.1" "sm man page"

.SH NAME
sm - Server Manager, tu amigable script de configuración

.SH DESCRIPCION

Este "simple" script te permite administrar varios aspectos del sistema sin lidiar con
la "complicada" línea de comandos

.SH OPCIONES

.IP -uyg|--users
    Abre directamente el menú de usuarios y grupos

.IP -red|--red
    Abre directamente el menú de gestión de red

.IP --gui
    Abre la interfáz

.IP --version|-v
    Muestra la version

.SH MOTTO

No aprendas bash, usa wrappers